config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "posts#index"

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @user = current_user
    @comment = Comment.find(params[:id]) ## Finding my comment id
    @show_user = @comment[:user_email]
    @post = Post.find(params[:post_id]) ## Finding my post id
  end

  def new ## this needs to render the post id (from the route) and that a comment is going to be new
    @user = current_user
    @post = Post.find(params[:post_id]) ##
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    redirect_to post_path(@post)
  end

  def edit ### this is going to need the post id and the comment id, (the form should be pre filled in)
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @user = current_user
  end

  def update
    @post = Post.find(params[:post_id])
    @user = current_user
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)

    redirect_to post_comment_path(@post, @comment)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:subject, :comment, :post_id, :user_id, :user_email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @user = current_user
    @post = Post.find(params[:id]) ## finding the post id
    @comments = Comment.where(:post_id => @post)
    @comment = Comment.new ## Finding my comment id
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create!(post_params)
    redirect_to post_path(@post) # Knows to get the id of this post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private # Anything defined under private is not a CRUD action and is just a helper to use in instances.
    def post_params
      params.require(:post).permit(:title, :content, :photo_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<div class="custom-layout">
<%= form_for ([@post, @comment]) do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>

  <%= f.label :comment %>
  <%= f.text_field :comment %>

  <%= f.hidden_field :user_id, :value => @user.id %>

  <%= f.hidden_field :user_email, :value => current_user.email %>

  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/comments/edit.html.erb
<div class="custom-layout">
<h3>Edit Comment</h3>

<%= render partial: "form" %>

<%= form_for [@post, @comment], method: :delete do |f| %>
  <%= f.submit "Delete Comment!", class: "button-delete" %>
<% end %>
</div>

app/views/comments/new.html.erb
<h3>New Comment</h3>

<%= render partial: "form" %>

app/views/comments/show.html.erb
<div class="custom-layout">
<h2>Comment:</h2>

<h3>"<%= @comment.subject %>" <%= link_to "(edit)", edit_post_comment_path %></h3>

<h4>By: <%= @show_user %></h4>

<p><%= @comment.comment %></p>

<%= form_for [@post, @comment], method: :delete do |f| %>
  <%= f.submit "Delete Comment!", class: "button-delete" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="nav">
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Home", root_path%></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>

  </div>

  <div class="container">

  <div class="sidebar">
    <header>
      <%= link_to image_tag("logo.png", class: "icon-logo"), root_path %>
      <div class="notice"><%= notice %></div>
      <div class="alert"><%= alert %></div>

    </header>
    <h2>Posts <%= link_to image_tag("plus.png", class: "icon-photo"), new_post_path %></h2>
    <% @posts = Post.all %>
    <% @posts.each do |post| %>
      <div class="sidebar_post">
          <%= link_to "#{post.title}", post_path(post) %>
      </div>
    <% end %>
  </div>

  <div class="content">
  <%= yield %>
  </div>

  </div>

  <div class="site-info">
		<p>©  Erica Andersen</p> | <p>Scribble 2015</p>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="custom-layout">
<%= form_for (@post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :photo_url, "Photo URL" %>
  <%= f.text_field :photo_url %>

  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="custom-layout">
<h2>Edit Post: <%= @post.title %></h2>

<%= render partial: "form" %>

<%= form_for @post, method: :delete do |f| %>
  <%= f.submit "Delete Post!" %>
<% end %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post">
    <div class="post-header">
      <span><%= link_to "#{post.title}", post_path(post) %></span>
      <p><%= post.created_at.strftime("%d %b %y") %></p>
    </div>

    <%= link_to image_tag(post.photo_url, class: "post-photo"), post_path(post) %>
    <p><%= post.content %></p>
    <div class="read-more">
      <%= link_to "Read Post", post_path(post) %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h3>New Posts</h3>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<div class="post">
  <div class="post-header">
  <span><%= @post.title %> <%= link_to image_tag("pencil.png", class: "icon-edit"), edit_post_path %></span>
  <p><%= @post.created_at.strftime("%d %b %y") %></p>
  </div>

  <%= image_tag @post.photo_url, class: "post-photo" %>

  <p><%= @post.content %></p>

  <h3>Comments <%= link_to image_tag("plus.png", class: "icon-photo"), new_post_comment_path(@post) %></h3>

  <% @comments.each do |comment| %>
    <div class = "comment">
    <h5><%= link_to "\"#{comment.subject}\"", post_comment_path(@post, comment) %></h5>
    <p>Added: <%= comment.created_at.strftime("%b %d %y") %> by: <%= comment.user_email %></p>
    <p><%= comment.comment %></p>
    </div>
  <% end %>

  <h3>Leave a comment:</h3>
  <%= render partial: "comments/form" %>
</div>